# Main configuration
url: http://docs.lv.com
title: Blazewater Documentation
description: Official documentation for building websites on the BaseKit platform
repository: https://github.com/skoroth/basekit

# Site details
facebook:
  page: Blazewater
  website: docs.lv.com

twitter: BaseKitDevs

# Jekyll options
exclude:
- CNAME
- LICENSE
- README.md
- bower_components
- bower.json
- gulpfile.js
- node_modules
- package.json

excerpt_separator: "\n\n"

# Permalinks
permalink: pretty

# Gems
gems:
- jemoji
- jekyll-sitemap

# Sass options
sass:
  style: compressed
